#!/usr/bin/env python3
#
# This file is part of blackman-mirrors.
# blackman-mirrors is a fork of Manjaro pacman-mirrors
#
# blackman-mirrors is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# blackman-mirrors is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with blackman-mirrors.  If not, see <http://www.gnu.org/licenses/>.
#
# Author(s): Ramon Buldó <rbuldo@gmail.com>

import os
import shutil
from blackman_mirrors import blackman_mirrors
from blackman_mirrors import i18n
from blackman_mirrors.configuration import O_CUST_FILE
from blackman_mirrors import bafn

_ = i18n.language.gettext


try:
    pm = blackman_mirrors.PacmanMirrors()
    pm.run()

except KeyboardInterrupt:
    print("\n" + _("Error: interrupted by the user."))
    exit(1)
